### ISSUE TITLE
模型架構

### ISSUE THREAD

**Issue by jyhsu2000** [HackerSir/HackerWebSite#1]
# 會員系統
- users
  - ID（INT(10)、AI、PK）
  - NID（VARCHAR(8)）
  - email（VARCHAR）
  - password（VARCHAR(60)）
  - name（VARCHAR(20)）
  - nickname（VARCHAR(20)）
  - job（VARCHAR(20)）
  - grade（VARCHAR(20)）
  - group_id（INT(10)）
  - remember_token（VARCHAR(100)）
  - confirm_code（VARCHAR(64)）
  - confirm_at（timestamp）
  - register_ip（VARCHAR(40)）
  - register_at（timestamp）
  - lastlogin_ip（VARCHAR(40)）
  - lastlogin_at（timestamp）
  - Laravel timestamps（create_at、update_at）
- password_resets
  - email（VARCHAR）
  - token（VARCHAR）
  - Laravel timestamps（create_at、update_at）
- groups
  - ID（INT(10)、AI、PK）
  - name（VARCHAR(20)）
  - title（VARCHAR(20)）
  - Laravel timestamps（create_at、update_at）
- courses
  - ID（INT(10)、AI、PK）
  - time（timestamp）
  - subject（VARCHAR(100)）
  - lecturer（VARCHAR(100)）
  - Laravel timestamps（create_at、update_at）
- signins
  - ID（INT(10)、AI、PK）
  - card_id（INT(10)）
  - course_id（INT(10)）
  - time（timestamp）
  - Laravel timestamps（create_at、update_at）
# 卡號與學號對照
- cards
  - ID（INT(10)、AI、PK）
  - NID（INT(10)）
  - card_number（VARCHAR(20)）
  - Laravel timestamps（create_at、update_at）

**Comment by vongola12324** [comment]
Login 是要做封印系統嗎？

**Comment by jyhsu2000** [comment]
@vongola12324 封印系統？0.0

**Comment by vongola12324** [comment]
@jyhsu2000 那個Login IP 啊～發現相同DDos攻擊來源就先把對面打下來在封鎖他（Ｘ

**Comment by jyhsu2000** [comment]
@vongola12324 自動反擊機制就靠強者學弟你了（拍肩

**Comment by jyhsu2000** [comment]
signins的`user_id`改為`card_id`
原因：
簽到者不見得是會員，但一定要有卡片
而如何在會員的介面查詢簽到記錄
就之後再改了...

**Comment by vongola12324** [comment]
@jyhsu2000 非社員不給電子簽到啊
也不會記錄到簽到單裡面（會有紙本的）

還是學長要弄成只記錄卡號，到時候對方入社時直接匯入這樣？

**Comment by jyhsu2000** [comment]
是想設計成只要有在手機刷卡登錄NID
就可以簽到
而不是刷卡登入NID之後
還要完成會員註冊才能簽到
只是沒註冊看不到自己的簽到記錄就是了

簽到流程：
如果是user_id：刷卡登錄NID->網站註冊->網站設定NID->簽到
如果是card_id：刷卡登錄NID->簽到

**Comment by vongola12324** [comment]
了解～

**Comment by jyhsu2000** [comment]
Move to wiki page [Model Structure](https://github.com/HackerSir/HackerWebSite/wiki/Model-Structure)
