### ISSUE TITLE
登入頁面及相關管理頁面啟用SSL

### ISSUE THREAD

**Issue by vongola12324** [HackerSir/HackerWebSite#11]
As Title.

SSL已經設定完畢，如果不看自簽的Error的話，一切正常運行中。
是否開啟SSL連線呢?  :closed_lock_with_key: 

@jyhsu2000 覺得呢？

**Comment by jyhsu2000** [comment]
強制HTTPS的middleware已經加上了 in 839dfbb
不過還沒有使用
是哪些地方需要呢？
- 整個站？
- 會員相關的？
- 只有登入跟註冊？

**Comment by vongola12324** [comment]
廣義來講，需要顯示任何個人資料的都要，除非是公開資料。
- 登入/註冊
- 後台

**Comment by jyhsu2000** [comment]
這樣說的話
除了503以外的所有頁面都要了
那我還是套用到整個網站好了...

**Comment by vongola12324** [comment]
@jyhsu2000 可是首頁不用.....(被打

**Comment by jyhsu2000** [comment]
首頁右上角會顯示暱稱...（個資無誤（？

**Comment by jyhsu2000** [comment]
首頁已經排除了
不過若被強制SSL之後
從https的路由
回到首頁
那依然會是https
這可能就無法處理了

**Comment by vongola12324** [comment]
Never Mind.

那如果把回到首頁的按鈕通通寫死http呢? (Ex: Navbar)

## 

不然就真的要把後臺跟首頁切割(次元切割刀意味

**Comment by jyhsu2000** [comment]
強制http技術上可行
不論是修改navbar路由連結方式
或是對https的首頁做重導向
應該都能做倒（理論上
但...有必要嗎？
一般網站不是保持https比較好嗎？

**Comment by vongola12324** [comment]
理論上是這樣，但是我們沒有CA，所以簽出來的憑證會噴警告

通常使用者看到噴警告就...........

**Comment by jyhsu2000** [comment]
Finished in 54bce26
