### ISSUE TITLE
首頁三大區塊（關於我們、社團課程、社團活動）

### ISSUE THREAD

**Issue by jyhsu2000** [HackerSir/HackerWebSite#15]
首頁三大區塊
關於我們、社團課程、社團活動
顯然需要有人協助

原訂是每個區塊一張圖片（或照片）
旁邊標題和一些文字
實際仍可能照需求修改

**Comment by vongola12324** [comment]
後兩個可不可以拿社課跟SITCON定期聚的相片來用啊？

另外我頃向找時間大家一起合拍張照片，放關於我們；還有拍每個人的大頭貼，放在幹部介紹？

**Comment by jyhsu2000** [comment]
似乎不錯
但或許要問問相官們？

**Comment by vongola12324** [comment]
@danny50610  麻煩幫我想一下介紹可以嗎QQ

**Comment by jyhsu2000** [comment]
參考社團簡介或之前的活動文如何？

**Comment by SCWhite** [comment]
可以放上次12越聚餐照片阿

**Comment by vongola12324** [comment]
@SCWhite 哪張OAO?放哪塊?

@jyhsu2000 想著要讓他通俗簡單點....但是好難QQ
