### ISSUE TITLE
VPS評估

### ISSUE THREAD

**Issue by timchengx** [HackerSir/HackerWebSite#18]
目前我們是掛在神秘的黑洞
考慮到那邊實質上不是我們的資源
所以是否要把東西搬到VPS上呢？

**Comment by jyhsu2000** [comment]
How about DigitalOcean?

**Comment by vongola12324** [comment]
承天奉運，社長詔曰：

主機先搬家啦！
@jyhsu2000 我會在一小時內把主機弄好，麻煩展元大幫忙備份社網跟系程的重要資料。
沒意外就用DigitalOcean先撐，錢一樣我先墊，直到下一步方案訂出來再做處理。
如未來有需要再討論，再重新開啟本issue。

欽此

**Comment by jyhsu2000** [comment]
社網目前沒啥資料需要備份
網站部分重新部署即可
（部署時也就能一併測試環境是否符合需求）
資料部分...
目前僅有的會員就你我兩人而已
重新註冊就好了啦A_A"

.env再複製過去或重新設定就好
