### ISSUE TITLE
URL::route連結參數

### ISSUE THREAD

**Issue by jyhsu2000** [HackerSir/HackerWebSite#22]
URL::route連結參數
某次更新後
變成「?」、「&」分隔
而非「/」
導致網站大量錯誤

**Comment by vongola12324** [comment]
似乎變成用傳統的GET?

**Comment by jyhsu2000** [comment]
應該是哪個套件的問題
3/24沒問題的版本...
有差異的部分
各套件版本編號：

| 套件 | 原版本 | 有問題的版本 |
| --- | --- | --- |
| laravel/framework | v5.0.18 | v5.0.21 |
| nesbot/carbon | 1.17.0 | 1.18.0 |
| nikic/php-parser | v1.2.0 | v1.2.1 |
| psy/psysh | v0.4.3 | v0.4.4 |

目前猜測
可能是Laravel框架本身的問題
具體還需要收集資料

**Comment by jyhsu2000** [comment]
Same issue on laravel repo
but it isn't be fixed yet
laravel/framework#8188

**Comment by jyhsu2000** [comment]
目前暫時解法...
![150327](https://cloud.githubusercontent.com/assets/6276648/6867700/8d393674-d4bf-11e4-99d3-bb2da5c9b05f.png)

**Comment by jyhsu2000** [comment]
Fix in Laravel v5.0.22
