### ISSUE TITLE
票數顯示頁 上方會亂碼

### ISSUE THREAD

**Issue by SCWhite** [HackerSir/HackerWebSite#25]
票數顯示那裏  上方欄都是亂碼的
要手切Unicode 
另外 "投票所"的選單也無法顯示
need fix

**Comment by timchengx** [comment]
幫補充資訊
使用firefox 顯示會呈現亂碼

**Comment by timchengx** [comment]
"投票所"的選單也無法顯示

視請況可能需要另開issue?

**Comment by SCWhite** [comment]
Chrome 也會
移動裝置還未測試

**Comment by SCWhite** [comment]
補充  手機端會炸掉 除了亂碼外
開兩次都在載入時當機 (我猜是畫圖的問題)
