### ISSUE TITLE
手機開統計頁面會當掉

### ISSUE THREAD

**Issue by vongola12324** [HackerSir/HackerWebSite#26]
Chrome可以正常跑第一輪，第二次更新會當掉。

**Comment by op8867555** [comment]
05d6ec7c 應該有改善

**Comment by danny50610** [comment]
經過一段波折，bug還是存在

**Comment by danny50610** [comment]
星期一(4/13) 和 @vongola12324 討論後

要不要先關掉 30s 更新，反正目前沒有開票了
而且可以避開當掉的問題

**Comment by jyhsu2000** [comment]
是時候該開分支了？OwO

**Comment by danny50610** [comment]
要開分支(branch)嗎?

**Comment by jyhsu2000** [comment]
主線的靜態化
分支的繼續處理刷新問題和手機問題
這樣如何？

還是直接靜態化
把那兩個問題留給明年的負責人？XD

**Comment by danny50610** [comment]
OK，
那主線先靜態化
怕後續一堆人抱怨網頁害手機當掉

分支等改造計畫確定再開啟
大概就慢慢改造。
