### ISSUE TITLE
課程列表建議

### ISSUE THREAD

**Issue by vongola12324** [HackerSir/HackerWebSite#28]
建議新增以下功能：
- 講師直接連結到每個人資料 （自動顯示使用者更新的暱稱）
- 追加簽到資料功能 （手動新增的意思）

**Comment by jyhsu2000** [comment]
由於考慮到講師不可能全部有帳號
目前為全自填
暫訂改為可填UID或字串

而簽到部分比較困難
畢竟簽到是「課程」跟「卡片」
只有會員而沒有卡片是無法簽到的
為了簽到而建立假卡號似乎也不太妥...

**Comment by vongola12324** [comment]
簽到要有系級、學號、姓名喔！
而且卡號是隱藏屬性，應該不顯示也不公開啊！

而我說的手動新增就是只填前三樣，卡號NULL的概念

**Comment by jyhsu2000** [comment]
以目前運行中的簽到系統
每次簽到包含**課程**與**卡片**
而卡片包含**學號**與**卡號**
不顯示與不公開是指看不到，而非不用存

如果真學號綁定假卡號
之後便無法在CCI上綁定同一組學號

所以是希望...
1. 大改目前的簽到系統架構？
2. 修改卡片資料格式與模型架構？（追加系級與姓名欄位，且系級、姓名、學號皆改為nullable，但之後系級與姓名只能管理人員人工輸入）
3. ~~有別於現行簽到系統，再創另一套並行使用？（似乎會很亂）~~

**Comment by jyhsu2000** [comment]
講師資料已支援UID in 52a47f1
舉例：
- 輸入數字2：自動對應UID為2的成員Vongola，並自動連結
- 輸入字串Danny：直接顯示Danny

**Comment by jyhsu2000** [comment]
卡片新增系級與姓名欄位
系級、姓名、卡號 設為 Nullable

需要卡片資料的系級與姓名時
- 若該NID為會員，並且有填寫系級與姓名，則從會員資料撈
- 若該NID不屬於會員，則直接從卡片資料的系級與姓名欄位取得

**Comment by jyhsu2000** [comment]
講師資料已完成
簽到相關移至 #30
