### ISSUE TITLE
網站美化

### ISSUE THREAD

**Issue by vongola12324** [HackerSir/HackerWebSite#3]
這邊先貼幾個目前發現已知的希望完成的東西：
- Navbar透明
- 上方連結除了Login通通改成用Section的方式？
- 接續上點，社網公開方式就一頁，分section來存ＯＫ嗎？

**Comment by jyhsu2000** [comment]
透明做的到
直接用rgba去覆寫原本的背景屬性

```
.navbar {
    background: rgba(72, 78, 85, 0.5);
}
```

![150305_3](https://cloud.githubusercontent.com/assets/6276648/6500607/bbb51866-c348-11e4-9197-066f40a0f779.png)

**Comment by vongola12324** [comment]
收到，那第二點呢？

**Comment by jyhsu2000** [comment]
兩種方案

1.
單純的標籤
連結：`<a href="#標籤">`或`<a href="網址#標籤">`
定位：`<section id="標籤">區塊內容</section>`
按下去會瞬間移動到那邊...

2.
以jQuary和CSS擴充上述方案
實現平滑滾動
甚至更強大的section分塊
如[fullPage套件](http://alvarotrigo.com/fullPage)

**Comment by jyhsu2000** [comment]
把fullPage.js裝上了
首頁也套用了
感覺還不錯
navbar的連結也可以順利對應
