### ISSUE TITLE
開票頁面訪客流量統計

### ISSUE THREAD

**Issue by danny50610** [HackerSir/HackerWebSite#31]
我想說用google做統計
等等4/8 16:00 來試試
可能會開PR

**Comment by jyhsu2000** [comment]
直接用公用帳號開Google Analytics吧
16點過來黑洞現場討論如何？
（雖然確實無難度可言）

**Comment by jyhsu2000** [comment]
Finish in d6315a9

**Comment by danny50610** [comment]
似乎有狀況
![default](https://cloud.githubusercontent.com/assets/3949245/7045407/712600aa-de30-11e4-9948-6b4a6d554374.png)

**Comment by danny50610** [comment]
似乎正常，再看看吧，抱歉

**Comment by jyhsu2000** [comment]
只是因為我們是自己建立JS去載入
所以他無法直接抓到那段代碼吧

把查詢的日期
改為到今天的話
能看到目前都是順利記錄的
