### ISSUE TITLE
首頁排版在"手機"會亂掉

### ISSUE THREAD

**Issue by danny50610** [HackerSir/HackerWebSite#34]
如題，排版有點亂
操作上會有點不順
似乎會有點lag(可能是我的手機問題)

**Comment by jyhsu2000** [comment]
表格都會炸掉...
無論哪個頁面

首頁套用fullPage.js
更導致navbar展開後無法捲動

**Comment by vongola12324** [comment]
是js的bug還是？
因為我這邊看是還好....不確定亂是怎樣的亂＠＠

**Comment by jyhsu2000** [comment]
Bootstrap的表格本身並沒有那麼完美的響應式顯示...
所以在手機版一定會超過section的大小

**Comment by danny50610** [comment]
等等我用電腦補圖

**Comment by danny50610** [comment]
![screenshot_2015-04-09-10-40-34](https://cloud.githubusercontent.com/assets/3949245/7062920/815066ec-ded4-11e4-8c37-6b87c1200aed.png)

**Comment by danny50610** [comment]
忘了關 Issue
在 #47 修正完成
(只有首頁)
