### ISSUE TITLE
Social Buttons

### ISSUE THREAD

**Issue by jyhsu2000** [HackerSir/HackerWebSite#36]
在「關於我們」放置FB社團、Github組織、Youtube連結...等
[Social Buttons for Bootstrap](http://lipis.github.io/bootstrap-social/)

**Comment by jyhsu2000** [comment]
貌似沒有Youtube圖標...

**Comment by danny50610** [comment]
要用這個嗎？
YouTube Subscribe Button: 
https://developers.google.com/youtube/youtube_subscribe_button

**Comment by jyhsu2000** [comment]
@danny50610 對齁...還有頻道訂閱按鈕可以用...
就這個了A_A
晚點再一起加上去

**Comment by jyhsu2000** [comment]
Finished in 8a0d5a8fcb5b60f55c54991cd6f9aa51d385f8d6
