### ISSUE TITLE
移動 Issues有 "Note筆記" Label 的內容 到 Wiki 

### ISSUE THREAD

**Issue by danny50610** [HackerSir/HackerWebSite#41]
想說開個 Wiki 存筆記

https://github.com/HackerSir/HackerWebSite/wiki/%E7%B6%B2%E7%AB%99%E9%96%8B%E7%99%BC%E5%AD%B8%E7%BF%92%E7%AD%86%E8%A8%98

看要不要把 移除 "Note筆記" Label

**Comment by jyhsu2000** [comment]
整理一些過去了
Label先留著吧
畢竟有些筆記可能是階段性的

**Comment by danny50610** [comment]
那Label 就留著吧
等其他有筆記的Issue 關閉時，再把筆記內容複製到 wiki 吧
