### ISSUE TITLE
get-token API

### ISSUE THREAD

**Issue by jyhsu2000** [HackerSir/HackerWebSite#42]
get-token API

**Comment by timchengx** [comment]
[**詳細**]

這是為了 ClassCheckIn (CCI) 所需要的 getToken API

CCI端輸入了HackerWebSite (HWS) 方的帳號密碼後
經過驗證 可以拿到一個有 **6小時時效**的 Token
CCI要跟HWS要任何資料時都會需要附上此 Token

**Comment by timchengx** [comment]
要求功能
- [ ] token 6hr 就失效

**Comment by jyhsu2000** [comment]
失效的token需要保留嗎？
預計每組token除了token和基本欄位之外
會有期限的欄位
因此可以實現，取得新token時，直接令前一組token立刻失效
優點：所有token皆能在任何時候反查擁有者

**Comment by timchengx** [comment]
有紀錄,聽起來不錯。

Todolist
- [ ] 實現後台反查token擁有者的功能
