### ISSUE TITLE
list-users API 修正

### ISSUE THREAD

**Issue by timchengx** [HackerSir/HackerWebSite#44]
4/26我們的討論說到
要把所有的 **社員資料** (不包括學生會, 還有其他在資料庫裡面的人)
可以抓下來

但是現在list-users API的功能是列出有綁定NID與卡片的人才會跑出來

所以是要
1. 另開一個新的 API 可以把[卡片清單](https://hackersir.info/card)的資料全部抓下來
2. 修改這個API 然後達到1.的功能?

@jyhsu2000 @danny50610

**Comment by timchengx** [comment]
#筆記
卡片清單的資料包含了
- NID
- 系級
- 姓名
- 卡號

**Comment by jyhsu2000** [comment]
先將list-users改為list-cards了
