### ISSUE TITLE
PureCSS 導入測試

### ISSUE THREAD

**Issue by vongola12324** [HackerSir/HackerWebSite#48]
目前開了個branch: pure-base
也在伺服器上開了新資料夾，麻煩幫我把以下功能拔掉:
- API
- Force HTTPS
- Login (保留畫面，但永遠登入失敗這樣)
- 清除log

**Comment by jyhsu2000** [comment]
Finished in 0f8ce1ed4d5dde11c4f197c31f15b9fc32c0b1c0
