### ISSUE TITLE
我們需要多一點貓

### ISSUE THREAD

**Issue by op8867555** [HackerSir/HackerWebSite#5]
http://thecatapi.com/docs.html

**Comment by vongola12324** [comment]
No Need (Some pic will be created in the future (ry

**Comment by jyhsu2000** [comment]
http://pixabay.com/
感覺有點強大的圖庫
高清、可做商業用途、無須署名、無版權限制
似乎也能找到不少小貓圖...

**Comment by timchengx** [comment]
需要貓貓支援 麻煩 @jyhsu2000 <_ _>

**Comment by jyhsu2000** [comment]
重點是...放哪？XD

**Comment by timchengx** [comment]
Error page?
開一個小類別(banner那種類別) ?
開每個網頁時有一定機率會變成貓貓圖?

可以當彩蛋來開發看看啦
但別把網站架構給破壞了說 (｀・ω・´)

**Comment by jyhsu2000** [comment]
Error page改成隨機小貓+錯誤訊息？

每個網頁有機率變貓貓圖的話...
會不會很煩呀？XDDD
例如想看社長帥氣照，卻發現社長是隻貓（誤

要放彩蛋是有很多方式啦
目前也有不少點子了（燦

**Comment by timchengx** [comment]
那就做吧 ＧＯ！

**Comment by jyhsu2000** [comment]
加上了
從Pixabay最新50張符合條件的圖隨機一張
可以到網站自己試試刷小貓（？

如果要本地測試
記得檢查`.env`和`.env.example`的項目
有新增相關設定
也要`composer update`

![150314](https://cloud.githubusercontent.com/assets/6276648/6644930/f65f25f0-c9f2-11e4-8ee5-bf1b39098a9f.png)

**Comment by timchengx** [comment]
感謝大大 <_ _<

2015-03-14 2:35 GMT+08:00 KID notifications@github.com:

**Comment by jyhsu2000** [comment]
Please re-open it if you think it's still needed.
