### ISSUE TITLE
Ask HTML/Android

### ISSUE THREAD

**Issue by vongola12324** [HackerSir/HackerWebSite#51]
我們之後會拿到HTML/Android課程的優惠卷，接著我們就要來看看要怎麼處理，我這邊有個點子，不知道各位的看法如何？

我們可以弄一個ask.hackersir.info，後面根據/html或是/android等等來做分類，每個就是開放他們根據類型來發問問題，然後我們可以回答他們幫忙解惑這樣。

舉例來說，我們可以將HTML劃分成：HTML5、CSS3、Javascript，讓在學習我們之後推的課程的學員，有地方可以發問不懂的地方。

@jyhsu2000  @danny50610 的看法？

**Comment by danny50610** [comment]
有沒有現成的論壇系統啊

**Comment by vongola12324** [comment]
有聽過的是Discuz

**Comment by bclin717** [comment]
PHPwind、 vBulletin、PHPBB

**Comment by vongola12324** [comment]
https://zh.wikipedia.org/wiki/Category:網絡討論區軟體

**Comment by vongola12324** [comment]
提案廢止。沒空。

**Comment by jyhsu2000** [comment]
雖然看起來好像錯過了
我還是回一下好了
ask.hackersir.info直接讓我想到ask.fm...

論壇系統比較常用又熟悉的就Discuz!和Discuz!X兩系列
phpBB也接觸過，但比較沒那麼強大
只是不論哪款...都不太容易跟現有的會員系統整合呀...

是說這個issue怎麼只存活兩小時呀？=w="
