### ISSUE TITLE
最後登入的IP紀錄不正確

### ISSUE THREAD

**Issue by danny50610** [HackerSir/HackerWebSite#52]
好像是因為有 CloudFlare 的關係

抓到的IP是CloudFlare的

![222b7460-2ef0-11e5-97a2-54f59c253f94](https://cloud.githubusercontent.com/assets/3949245/8843662/013390da-313e-11e5-95d5-e4de2c639ef6.png)

CloudFlare似乎有提供 Apache 的模組，但不確定是否為正確解法
https://www.cloudflare.com/resources-downloads#mod_cloudflare

**Comment by vongola12324** [comment]
Fixed.

Use [How do I restore original visitor IP with Apache 2.4?](https://support.cloudflare.com/hc/en-us/articles/203656534-How-do-I-restore-original-visitor-IP-with-Apache-2-4-)

If there's still having any problem, plz create a new issue.

Vongola
