### ISSUE TITLE
成員資料公開

### ISSUE THREAD

**Issue by vongola12324** [HackerSir/HackerWebSite#7]
這邊我規劃是分成兩部分：
- staff.hackersir.info
  這個是規劃中拿來放所有幹部、社員列表的網站，到時候CCI可能也是來這邊爬（我想
- hackersir.info
  這個是黑客社首頁，會顯示的應該只有歷屆幹部，不顯示社員。

**Comment by jyhsu2000** [comment]
看來該找時間研究一下Laravel的子網域路由了...
不過直接`hackersir.info/staff`應該會比較好寫吧？
畢竟一般用`Route::controller`或`Route::resource`都是直接把網址後第一個參數去對應controller的function

不過CCI不是只要用API嗎？
API應該也全都會放在`hackersir.info/api/動作`
所有需要的資料都從API取得應該就好了吧
感覺不太需要直接存取網頁端

**Comment by vongola12324** [comment]
只是一個構想....(乾笑

**Comment by jyhsu2000** [comment]
還是先想想可見度就好了...
**幹部、成員** 分別看的到 **幹部、成員** 的哪些資料？
至於遊客就無視了，反正遊客看不到那些頁面

**Comment by vongola12324** [comment]
staff.hackersir.info -> 幹部Only -> 可以看全社社員資料
- NID
- 系級
- 姓名
- 信箱

PS: 我們不是也只有收這些資料嗎？

hackersir.info -> AnyOne -> 顯示歷任幹部

**Comment by jyhsu2000** [comment]
所以都一樣那些資料都有
不過幹部可以看到所有人的
而社員只能看到幹部的？

**Comment by vongola12324** [comment]
也是可以，還是有要嚴格到只有會碰到社員資料的才能看嗎？

**Comment by jyhsu2000** [comment]
還是要把幹部跟工作人員的群組分開？
或是User新增一個屬性來判定是否為網站工作人員？

**Comment by vongola12324** [comment]
有辦法群組中群組嗎？

Ex: 幹部中在分學術、事務這樣？

**Comment by jyhsu2000** [comment]
目前只能一個階層
而且每人只能屬於一個群組
users的group_id
去對應groups

**Comment by vongola12324** [comment]
那就讓幹部都開看的到吧，比較簡單....

**Comment by jyhsu2000** [comment]
也是...
要擴充之後再擴充吧...

**Comment by vongola12324** [comment]
等等.....你想擴充什麼？之後應該是縮限了吧！
在擴充下去就連遊客都可以看到啦！（咦？

**Comment by jyhsu2000** [comment]
是指功能看權限分配的自由度啦XDDDD
要擴大開放的話也不是不行啦
社長的資料...（X

**Comment by vongola12324** [comment]
@jyhsu2000 請別這麼做ＱＨＱ
我們不能改公開吉祥物的資料嗎（誤

那就等學長確定權限實作狀況囉ＯＡＯ？

**Comment by jyhsu2000** [comment]
目前想法...

基本資料：（幹部可看到所有人的，社員可看到幹部的）
- 大頭貼（Gravatar）
- 真實姓名
- 暱稱
- 系級
- 信箱（附註是否完成驗證）

幹部可額外看到所有人的：
- NID
- 是否綁定卡片（但看不到卡片號碼）
- 註冊時間、IP
- 最後登錄時間、IP

**Comment by jyhsu2000** [comment]
Please re-open it if you think it's still needed.
